[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_science = "G9sh8zEyXBzXRhRUj5nwbjQPNaeu1uPE7g5UBRNSs17Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
