[toolchain]

[features]
resolution = true
skip-lint = false



[programs.localnet]
pump_science = "6xyCEeyVb1RzDB9Tq6jNfMaCAGvzdWJg6K7rRhjNR4fk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"